language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed emanjamal/udagram-api-feed:v1
  - docker tag udagram-api-user emanjamal/udagram-api-user:v1
  - docker tag udagram-frontend emanjamal/udagram-frontend:v1
  - docker tag reverseproxy emanjamal/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push emanjamal/udagram-api-feed
  - docker push emanjamal/udagram-api-user
  - docker push emanjamal/udagram-frontend
  - docker push emanjamal/reverseproxy